return {
    ---@param cutscene WorldCutscene
    martlet = function(cutscene, event)
        local martlet = cutscene:getCharacter("martlet")
        Game.world.music:fade(0, 0.5)
        cutscene:text("* Now,[wait:5] let's see here...", nil, "martlet")
        cutscene:wait(cutscene:panTo(300, 760, 2))
        Game.world.music:play("birdsofafeather", 1)
        cutscene:text("* Okay,[wait:5] this should be it for now!", nil, "martlet")
        martlet:setFacing("down")
        --cutscene:wait(cutscene:walkTo(martlet, martlet.x, martlet.y + 40, 0.3, "down")) -- walking animation NOT works
        cutscene:text("* Now all that left is-[wait:5]", "content", "martlet", {auto=true})
        martlet:alert()
        cutscene:wait(1)
        cutscene:text("* O-[wait:5]oh,[wait:5] hello there!", "surprised", "martlet")
        cutscene:text("* I didn't really expect to see anyone here.", "melancholic", "martlet")
        cutscene:text("* Hey,[wait:5] I don't think I've seen you before.[wait:10] That's weird...", "confused", "martlet")
        cutscene:text("* Because I know almost ALL residents of lower Snowdin.", "questioning", "martlet")
        cutscene:text("* Well,[wait:5] nice to meet you anyway.", "regular", "martlet")
        cutscene:text("* I'm [color:5CBAF9]Martlet[color:reset].", "wink", "martlet")
        cutscene:text("* I live here.", "regular", "martlet")
        cutscene:text("* ...", "moderate", "martlet")
        cutscene:text("* Or,[wait:5] rather,[wait:5] I was.", "wondering", "martlet")
        cutscene:text("* You see,[wait:5] you kind of caught me in the middle of moving.", "nervous_smile", "martlet")
        cutscene:text("* Hey,[wait:5] I know this is a little sudden,[wait:5] but...", "melancholic", "martlet")
        cutscene:text("* You think you could help me with-[wait:5]", "regular", "martlet", {auto=true})
        Assets.playSound("phone")
        cutscene:wait(0.5)
        Assets.playSound("phone")
        cutscene:wait(1)
        cutscene:text("* Oh,[wait:5] that's my alarm.[wait:10] I gotta go.", "nervous_smile", "martlet")
        cutscene:text("* But,[wait:5] hey,[wait:5] if you ever will be in [color:yellow]town[color:reset]...", "regular", "martlet")
        cutscene:text("* (I mean the one on the surface,[wait:5] obviously.)", "suspiciouser", "martlet")
        cutscene:text("* Feel free to pay a visit to me.", "smirk", "martlet")
        cutscene:text("* Okay,[wait:5] I REALLY gotta get going.", "nervous_smile", "martlet")
        cutscene:text("* See ya around!", "wink", "martlet")
        Assets.playSound("martlet_takeoff")
        martlet:setAnimation("fly_away")
        cutscene:wait(0.5)
        Game.world.music:fade(0, 0.5)
        cutscene:wait(2)
        martlet:remove()
        cutscene:wait(cutscene:attachCamera(2))
        Game.world.music:play("snowfall", 1)
        Game:setFlag("martlet_met", true)
    end
}
