return {
    martlet = function(cutscene, event)
        local martlet = cutscene:getCharacter("martlet")
        Game.world.music:fade(0, 0.5)
        if Game:getFlag("EMPTIED_SNOWDIN_YELLOW") then
            martlet:setFacing("down")
            cutscene:showNametag("???")
            cutscene:text("* There you are!", nil, "martlet")
            cutscene:hideNametag()
            cutscene:wait(cutscene:panTo(300, 760, 2))
            cutscene:showNametag("Bird lady")
            cutscene:text("* ...", "angry", "martlet")
            cutscene:text("* I saw what you did.", "angry", "martlet")
            cutscene:text("* I was just flying by,[wait:5] when I heard some trouble.", "unamused", "martlet")
            cutscene:text("* I decided to investigate,[wait:5] and...", "wondering", "martlet")
            cutscene:text("* ...saw how you killed those innocent bystanders.", "angrier", "martlet")
            cutscene:text("* ...", "downer", "martlet")
            cutscene:text("* I should've intervened.", "sad", "martlet")
            cutscene:text("* I could've saved at least a few.", "downer", "martlet")
            cutscene:hideNametag()
            cutscene:wait(1)
            cutscene:showNametag("Bird lady")
            cutscene:text("* You wanna do the same to me,[wait:5] don't you?", "angry", "martlet")
            cutscene:text("* I'm not stupid.[wait:10] I know I stand no chance against you.", "unamused", "martlet")
            cutscene:text("* I'll go and warn the others about you.", "angry", "martlet")
            cutscene:text("* That's the least I can do.", "sad", "martlet")
            cutscene:text("* So you better stop with that...[wait:10] Slaughter.", "angry", "martlet")
            cutscene:text("* Or you gonna have some serious problems.", "unamused", "martlet")
            cutscene:hideNametag()
        else
            cutscene:showNametag("???")
            cutscene:text("* Now,[wait:5] let's see here...", nil, "martlet")
            cutscene:hideNametag()
            cutscene:wait(cutscene:panTo(300, 760, 2))
            Game.world.music:play("birdsofafeather", 1)
            cutscene:showNametag("Bird lady")
            cutscene:text("* Okay,[wait:5] this should be it for now!", nil, "martlet")
            cutscene:hideNametag()
            martlet:setFacing("down")
            --cutscene:wait(cutscene:walkTo(martlet, martlet.x, martlet.y + 40, 0.3, "down")) -- walking animation NOT works
            cutscene:showNametag("Bird lady")
            cutscene:text("* Now all that left is-[wait:5]", "content", "martlet", {auto=true})
            cutscene:hideNametag()
            martlet:alert()
            cutscene:wait(1)
            cutscene:showNametag("Bird lady")
            cutscene:text("* O-[wait:5]oh,[wait:5] hello there!", "surprised", "martlet")
            cutscene:text("* I didn't really expect to see anyone here.", "melancholic", "martlet")
            cutscene:text("* Hey,[wait:5] I don't think I've seen you before.[wait:10] That's weird...", "confused", "martlet")
            cutscene:text("* Because I know almost ALL residents of lower Snowdin.", "questioning", "martlet")
            cutscene:text("* Well,[wait:5] nice to meet you anyway.", "regular", "martlet")
            cutscene:showNametag("Martlet")
            cutscene:text("* I'm [color:5CBAF9]Martlet[color:reset].", "wink", "martlet")
            cutscene:text("* I live here.", "regular", "martlet")
            cutscene:text("* ...", "moderate", "martlet")
            cutscene:text("* Or,[wait:5] rather,[wait:5] I was.", "wondering", "martlet")
            cutscene:text("* You see,[wait:5] you kind of caught me in the middle of moving.", "nervous_smile", "martlet")
            cutscene:text("* Hey,[wait:5] I know this is a little sudden,[wait:5] but...", "melancholic", "martlet")
            cutscene:text("* You think you could help me with-[wait:5]", "regular", "martlet", {auto=true})
            cutscene:hideNametag()
            Assets.playSound("phone")
            cutscene:wait(0.5)
            Assets.playSound("phone")
            cutscene:wait(1)
            cutscene:showNametag("Martlet")
            cutscene:text("* Oh,[wait:5] that's my alarm.[wait:10] I gotta go.", "nervous_smile", "martlet")
            cutscene:text("* But,[wait:5] hey,[wait:5] if you ever will be in [color:yellow]town[color:reset]...", "regular", "martlet")
            cutscene:text("* (I mean the one on the surface,[wait:5] obviously.)", "suspiciouser", "martlet")
            cutscene:text("* Feel free to pay a visit to me.", "smirk", "martlet")
            cutscene:text("* Okay,[wait:5] I REALLY gotta get going.", "nervous_smile", "martlet")
            cutscene:text("* See ya around!", "wink", "martlet")
            cutscene:hideNametag()
        end
        Assets.playSound("martlet_takeoff")
        martlet:setAnimation("fly_away")
        cutscene:wait(0.5)
        Game.world.music:fade(0, 0.5)
        cutscene:wait(2)
        martlet:remove()
        cutscene:wait(cutscene:attachCamera(2))
        Game.world.music:play("snowfall", 1)
        Game:setFlag("martlet_met", true)
    end
}
