local Basic, super = Class(LightWave)

function Basic:init()
    super.init(self)
    self.time = 99
    self.flowers = false
    self.flowers_big = false
    self.beams = false
end

function Basic:onStart()
    local arena = Game.battle.arena
    self.timer:after(1, function()
        Game.battle.music:play("trial_by_fury_2", 1, 1.1)
        arena:changePosition({320, 240})
        arena:changeShape({640, 480})
    end)
    --self.timer:after(2, function() self.flowers = true end)
    self.timer:every(0.1, function()
        if self.flowers then
            local LorR = Utils.pick({1, 2})
            if LorR == 1 then
                self:spawnBullet("ceroba/flower", arena.left, love.math.random(1, 480), math.rad(0), 2)
            else
                self:spawnBullet("ceroba/flower", arena.right, love.math.random(1, 480), math.rad(180), 2)
            end
        end
    end)
    self.timer:after(2.5, function()
        local b = self:spawnBullet("ceroba/flower_large", arena.width/3, 520, math.rad(270), 20, 0.5, true, "b")
        local b2 = self:spawnBullet("ceroba/flower_large", arena.width/3*2, 520, math.rad(270), 20, 0.5, true, "b")
        self.timer:after(1, function()
            b:shootFlowers()
            b2:shootFlowers()
        end)
        self.timer:after(1.5, function()
            b:explodeFlower()
            b2:explodeFlower()
        end)
    end)
    self.timer:after(3.5, function()
        local b = self:spawnBullet("ceroba/flower_large", arena.width/2, 520, math.rad(270), 20, 0.5, true, "o")
        self.timer:after(1, function() b:shootFlowers() end)
        self.timer:after(1.5, function() b:explodeFlower() end)
        self.timer:after(0.3, function()
            local b2 = self:spawnBullet("ceroba/flower_large", arena.width/6, 520, math.rad(270), 20, 0.5, true, "o")
            local b3 = self:spawnBullet("ceroba/flower_large", arena.width/6*5, 520, math.rad(270), 20, 0.5, true, "o")
            self.timer:after(1, function()
                b2:shootFlowers()
                b3:shootFlowers()
            end)
            self.timer:after(1.5, function()
                b2:explodeFlower()
                b3:explodeFlower()
            end)
        end)
    end)
    self.timer:after(7, function()
        self:spawnBullet("ceroba/beam", 20, 240, 90, 5)
        self:spawnBullet("ceroba/beam", 620, 240, 90, 5)
        self.timer:after(0.5, function()
            self:spawnBullet("ceroba/beam", 60, 240, 90, 4.5)
            self:spawnBullet("ceroba/beam", 580, 240, 90, 4.5)
            self.timer:after(0.5, function()
                self:spawnBullet("ceroba/beam", 100, 240, 90, 4)
                self:spawnBullet("ceroba/beam", 540, 240, 90, 4)
                self.timer:after(0.5, function()
                    self:spawnBullet("ceroba/beam", 140, 240, 90, 3.5)
                    self:spawnBullet("ceroba/beam", 500, 240, 90, 3.5)
                    self.timer:after(0.5, function()
                        self:spawnBullet("ceroba/beam", 180, 240, 90, 3)
                        self:spawnBullet("ceroba/beam", 460, 240, 90, 3)
                        self.timer:after(0.5, function()
                            self:spawnBullet("ceroba/beam", 220, 240, 90, 2.5)
                            self:spawnBullet("ceroba/beam", 420, 240, 90, 2.5)
                            self.timer:after(0.5, function()
                                self:spawnBullet("ceroba/beam", 260, 240, 90, 2)
                                self:spawnBullet("ceroba/beam", 380, 240, 90, 2)
                            end)
                        end)
                    end)
                end)
            end)
        end)
    end)
    self.timer:after(13, function()
        self.flowers_big = true
        self.timer:after(1, function() Assets.playSound("decibatbouncewave2") end)
        self.timer:every(1, function()
            if self.flowers_big then
                self:spawnBullet("ceroba/flower_large", arena.left-30, 20, math.rad(0), 3.5)
                self:spawnBullet("ceroba/flower_large", arena.right+30, 60, math.rad(180), 3.5)
                self:spawnBullet("ceroba/flower_large", arena.left-30, 100, math.rad(0), 3.5)
                self:spawnBullet("ceroba/flower_large", arena.right+30, 140, math.rad(180), 3.5)
                self:spawnBullet("ceroba/flower_large", arena.left-30, 180, math.rad(0), 3.5)
                self:spawnBullet("ceroba/flower_large", arena.right+30, 220, math.rad(180), 3.5)
                self:spawnBullet("ceroba/flower_large", arena.left-30, 260, math.rad(0), 3.5)
                self:spawnBullet("ceroba/flower_large", arena.right+30, 300, math.rad(180), 3.5)
                self:spawnBullet("ceroba/flower_large", arena.left-30, 340, math.rad(0), 3.5)
                self:spawnBullet("ceroba/flower_large", arena.right+30, 380, math.rad(180), 3.5)
                self:spawnBullet("ceroba/flower_large", arena.left-30, 420, math.rad(0), 3.5)
                self:spawnBullet("ceroba/flower_large", arena.right+30, 460, math.rad(180), 3.5)
            end
        end)
        self.timer:after(2, function()
            self:spawnBullet("ceroba/beam", 320, 20, 0, 6)
            self:spawnBullet("ceroba/beam", 320, 460, 0, 6)
            self.timer:after(1, function()
                self:spawnBullet("ceroba/beam", 320, 60, 0, 5)
                self:spawnBullet("ceroba/beam", 320, 420, 0, 5)
                self.timer:after(1, function()
                    self:spawnBullet("ceroba/beam", 320, 100, 0, 4)
                    self:spawnBullet("ceroba/beam", 320, 380, 0, 4)
                    self.timer:after(1, function()
                        self:spawnBullet("ceroba/beam", 320, 140, 0, 3)
                        self:spawnBullet("ceroba/beam", 320, 340, 0, 3)
                        self.timer:after(1, function()
                            self:spawnBullet("ceroba/beam", 320, 180, 0, 2)
                            self:spawnBullet("ceroba/beam", 320, 300, 0, 2)
                        end)
                    end)
                end)
            end)
        end)
    end)
    self.timer:after(21, function() self.flowers_big = false end)
    self.timer:after(23, function()
        self.beams = true
        self.timer:every(0.5, function()
            if self.beams then
                self:spawnBullet("ceroba/beam", love.math.random(20, 620), love.math.random(20, 460), math.rad(love.math.random(1, 360)))
            end
        end)
    end)
end

function Basic:update()

    super.update(self)
end

return Basic