local Basic, super = Class(LightWave)

function Basic:init()
    super:init(self)
    self:setArenaSize(256, 180)
    --self:setArenaPosition(319, 320) -- orig 320, 385
    self.time = 11
end

function Basic:shotOne()
    Assets.playSound("ceroba_bullet_shot")
    self:spawnBullet("ceroba/flower", self.bigflower.x, self.bigflower.y, math.rad(180), 4)
    self:spawnBullet("ceroba/flower", self.bigflower.x, self.bigflower.y, math.rad(190), 4)
    self:spawnBullet("ceroba/flower", self.bigflower.x, self.bigflower.y, math.rad(200), 4)
    self:spawnBullet("ceroba/flower", self.bigflower.x, self.bigflower.y, math.rad(170), 4)
    self:spawnBullet("ceroba/flower", self.bigflower.x, self.bigflower.y, math.rad(160), 4)
end

function Basic:onStart()
    Assets.playSound("ceroba_bullet_rise", 1.5)
    self.bigflower = self:spawnBullet("ceroba/flower_large", SCREEN_WIDTH + 40, Game.battle.arena.y)
    self.timer:after(1/2, function()
        Assets.playSound("decibatbouncewave2", 1.5)
        self.bigflower:slideTo(Game.battle.arena.right + 40, self.bigflower.y, 0.4)
    end)
    self.timer:after(0.5, function()
        self.timer:after(0.5, function()
            self:shotOne()
            self.bigflower:slideTo(self.bigflower.x, Game.battle.arena.y - Game.battle.arena.height/4, 0.4)
        end)
        self.timer:after(1, function()
            self:shotOne()
            self.bigflower:slideTo(self.bigflower.x, Game.battle.arena.y + Game.battle.arena.height/4, 0.4)
        end)
        self.timer:after(1.5, function()
            self:shotOne()
            self.bigflower:slideTo(self.bigflower.x, Game.battle.arena.y, 0.4)
        end)
        self.timer:after(2, function()
            self:shotOne()
            self.bigflower:slideTo(self.bigflower.x, Game.battle.arena.y - Game.battle.arena.height/4, 0.4)
        end)
        self.timer:after(2.5, function()
            self:shotOne()
            self.timer:after(0.2, function()
                Assets.playSound("bombfall", 1.5)
                self.bigflower:setColor(1, 0, 0)
                self.timer:after(0.1, function()
                    self.bigflower:setColor(1, 1, 1)
                end)
            end)
            self.timer:after(0.4, function()
                Assets.playSound("bombfall", 1.5)
                self.bigflower:setColor(1, 0, 0)
                self.timer:after(0.1, function()
                    self.bigflower:setColor(1, 1, 1)
                end)
            end)
            self.timer:after(0.6, function()
                Assets.playSound("bombfall", 1.5)
                self.bigflower:setColor(1, 0, 0)
                self.timer:after(0.1, function()
                    self.bigflower:setColor(1, 1, 1)
                end)
            end)
            self.timer:after(0.8, function()
                self:spawnBullet("ceroba/explosion", self.bigflower.x, self.bigflower.y)
                Game.battle.camera:shake(4, 2, 0.5)
                self.bigflower:remove()
            end)
            self.timer:after(1.3, function()
                self:spawnBullet("ceroba/ring_o", self.bigflower.x, self.bigflower.y)
            end)
        end)
        self.timer:after(4.5, function()
            self:spawnBullet("ceroba/beam", Game.battle.arena.x, Game.battle.arena.top + 20)
            self:spawnBullet("ceroba/beam", Game.battle.arena.x, Game.battle.arena.bottom - 20)
            self.timer:after(0.5, function()
                self:spawnBullet("ceroba/beam", Game.battle.arena.x, Game.battle.arena.top + 50)
                self:spawnBullet("ceroba/beam", Game.battle.arena.x, Game.battle.arena.bottom - 50)
            end)
            self.timer:after(1.5, function()
                self:spawnBullet("ceroba/beam", Game.battle.arena.x, Game.battle.arena.y)
            end)
            self.timer:after(2, function()
                local bigflower4 = self:spawnBullet("ceroba/flower_large", Game.battle.arena.x, -40)
                bigflower4:slideTo(bigflower4.x, Game.battle.arena.bottom, 1)
                self.timer:after(1, function()
                    self:spawnBullet("ceroba/explosion", bigflower4.x, bigflower4.y)
                    Game.battle.camera:shake(4, 2, 0.5)
                    self.timer:after(0.5, function()
                        self:spawnBullet("ceroba/ring_b", bigflower4.x, bigflower4.y)
                    end)
                    bigflower4:remove()
                end)
            end)
            self.timer:after(3.5, function()
                self:spawnBullet("ceroba/diamond", Game.battle.soul.x, Game.battle.soul.y)
            end)
        end)

        self.timer:after(1, function()
            local bigflower2 = self:spawnBullet("ceroba/flower_large", Game.battle.arena.x - Game.battle.arena.width/4, -40)
            bigflower2:slideTo(bigflower2.x, Game.battle.arena.bottom, 1)
            self.timer:after(1, function()
                self:spawnBullet("ceroba/explosion", bigflower2.x, bigflower2.y)
                Game.battle.camera:shake(4, 2, 0.5)
                self.timer:after(0.5, function()
                    self:spawnBullet("ceroba/ring_b", bigflower2.x, bigflower2.y)
                end)
                bigflower2:remove()
            end)
        end)
        self.timer:after(1.5, function()
            local bigflower3 = self:spawnBullet("ceroba/flower_large", Game.battle.arena.x + Game.battle.arena.width/4, -40)
            bigflower3:slideTo(bigflower3.x, Game.battle.arena.bottom, 1)
            self.timer:after(1, function()
                self:spawnBullet("ceroba/explosion", bigflower3.x, bigflower3.y)
                Game.battle.camera:shake(4, 2, 0.5)
                self.timer:after(0.5, function()
                    self:spawnBullet("ceroba/ring_b", bigflower3.x, bigflower3.y)
                end)
                bigflower3:remove()
            end)
        end)
    end)
end

function Basic:update()

    super.update(self)
end

return Basic