return {
    intro = function(cutscene, battler, enemy)
        local ceroba = Game.battle:getEnemyBattler("ceroba_geno")
        ceroba:getActiveSprite():setAnimation("intro")
        cutscene:wait(2.5)
        ceroba:toggleOverlay(false)
        cutscene:battlerText(ceroba, "...")
        cutscene:battlerText(ceroba, "...")
        cutscene:battlerText(ceroba, "Why...")
        cutscene:battlerText(ceroba, "Why have you\ndone this?")
        cutscene:battlerText(ceroba, "Is it because\nof some personal\ncrusade?")
        cutscene:battlerText(ceroba, "Your species already\nimprisoned us here.\nYou won.")
        cutscene:battlerText(ceroba, "I don't understand...")
        cutscene:battlerText(ceroba, "...")
        cutscene:battlerText(ceroba, "Chujin was right\nall along.")
        cutscene:battlerText(ceroba, "Humans want to rule\nover us;\ncontrol our lives...")
        cutscene:battlerText(ceroba, "Even if we freed\nourselves, they would\nonly wage war again.")
        cutscene:battlerText(ceroba, "If only I stayed\nhere and didn't\nrun off, I could've\nprotected St-")
        cutscene:battlerText(ceroba, "Enough talk.")
        cutscene:battlerText(ceroba, "Starlo was the...\nthe only friend\nI had left.")
        cutscene:battlerText(ceroba, "What you've done\nis unforgivable.")
        cutscene:battlerText(ceroba, "... ")
        cutscene:battlerText(ceroba, "You WILL know the\npain you have caused.")

        cutscene:after(function()
            Game.battle:setState("ACTIONSELECT")
        end, true)
    end,
    death = function(cutscene, battler, enemy)
        Game.battle.music:stop()
        local ceroba = Game.battle:getEnemyBattler("ceroba_geno")
        cutscene:wait(1.5)
        ceroba:getActiveSprite():setAnimation("death")
        cutscene:wait(2.5)
        --ceroba:toggleOverlay(false)
        cutscene:battlerText(ceroba, "...")
        cutscene:battlerText(ceroba, "Look.")
        cutscene:battlerText(ceroba, "Look at me, coward!")
        cutscene:battlerText(ceroba, "The fruits of your\nlabor.")
        cutscene:battlerText(ceroba, "Does this make\nyou happy?")
        cutscene:battlerText(ceroba, "Maybe if I were to\nbeg for mercy.")
        cutscene:battlerText(ceroba, "Make you feel bad\nabout your actions?")
        cutscene:battlerText(ceroba, "No...")
        cutscene:battlerText(ceroba, "...")
        cutscene:battlerText(ceroba, "Once you wipe\nus out...")
        cutscene:battlerText(ceroba, "...I hope you choke on\nthe dust that will\nfill the air.")
        cutscene:battlerText(ceroba, "...")
        cutscene:battlerText(ceroba, "...In the meantime...")
        cutscene:battlerText(ceroba, "Go to Hell.")

        ceroba:getActiveSprite():setSprite("dead")
        ceroba:onDefeatVaporized(damage, battler)
        cutscene:after(function()
            Game.battle:setState("VICTORY")
        end, true)
    end,
    phase_switch = function(cutscene, battler, enemy)
        Game.battle.music:stop()
        local ceroba = Game.battle:getEnemyBattler("ceroba_geno")
        cutscene:wait(0.2)
        ceroba:toggleOverlay(true)
        ceroba:getActiveSprite():setAnimation("phase_switch")
        Assets.playSound("staff_spin")
        cutscene:wait(2)
        Assets.playSound("ceroba_yell")
        Game.battle.music:play("trial_by_fury_2")
        cutscene:wait(2)
        ceroba:setActor("cerobaboss_p2")
        Game.battle:setState("DEFENDINGEND")
        cutscene:wait(0.5)

        cutscene:after(function()
            Game.battle:setState("ENEMYDIALOGUE")
        end, true)
    end,
    pacify = function(cutscene, battler, enemy)
        Game.battle.battle_ui:clearEncounterText()
        Game.battle.music:stop()
        local ceroba = Game.battle:getEnemyBattler("ceroba_geno")
        cutscene:wait(2.5)
        cutscene:battlerText(ceroba, {"Do you really\nthink...", "That after all\nyou've done..."})

        Game.battle:toggleSoul(true)
        Game.battle.arena:changeShape({16, 16})
        cutscene:wait(1)

        Assets.playSound("noise")
        local bullet1 = Sprite("battle/bullets/ceroba/flower")
        bullet1:setPosition(Game.battle.soul.x, Game.battle.soul.y - 30)
        bullet1.layer = Game.battle.soul.layer + 1
        bullet1:setOrigin(0.5, 0.5)
        Game.battle.soul.parent:addChild(bullet1)
        cutscene:wait(0.1)
        Assets.playSound("noise")
        local bullet2 = Sprite("battle/bullets/ceroba/flower")
        bullet2:setPosition(Game.battle.soul.x + 20, Game.battle.soul.y - 20)
        bullet2.layer = Game.battle.soul.layer + 1
        bullet2:setOrigin(0.5, 0.5)
        Game.battle.soul.parent:addChild(bullet2)
        cutscene:wait(0.1)
        Assets.playSound("noise")
        local bullet3 = Sprite("battle/bullets/ceroba/flower")
        bullet3:setPosition(Game.battle.soul.x + 30, Game.battle.soul.y)
        bullet3.layer = Game.battle.soul.layer + 1
        bullet3:setOrigin(0.5, 0.5)
        Game.battle.soul.parent:addChild(bullet3)
        cutscene:wait(0.1)
        Assets.playSound("noise")
        local bullet4 = Sprite("battle/bullets/ceroba/flower")
        bullet4:setPosition(Game.battle.soul.x + 20, Game.battle.soul.y + 20)
        bullet4.layer = Game.battle.soul.layer + 1
        bullet4:setOrigin(0.5, 0.5)
        Game.battle.soul.parent:addChild(bullet4)
        cutscene:wait(0.1)
        Assets.playSound("noise")
        local bullet5 = Sprite("battle/bullets/ceroba/flower")
        bullet5:setPosition(Game.battle.soul.x, Game.battle.soul.y + 30)
        bullet5.layer = Game.battle.soul.layer + 1
        bullet5:setOrigin(0.5, 0.5)
        Game.battle.soul.parent:addChild(bullet5)
        cutscene:wait(0.1)
        Assets.playSound("noise")
        local bullet6 = Sprite("battle/bullets/ceroba/flower")
        bullet6:setPosition(Game.battle.soul.x - 20, Game.battle.soul.y + 20)
        bullet6.layer = Game.battle.soul.layer + 1
        bullet6:setOrigin(0.5, 0.5)
        Game.battle.soul.parent:addChild(bullet6)
        cutscene:wait(0.1)
        Assets.playSound("noise")
        local bullet7 = Sprite("battle/bullets/ceroba/flower")
        bullet7:setPosition(Game.battle.soul.x - 30, Game.battle.soul.y)
        bullet7.layer = Game.battle.soul.layer + 1
        bullet7:setOrigin(0.5, 0.5)
        Game.battle.soul.parent:addChild(bullet7)
        cutscene:wait(0.1)
        Assets.playSound("noise")
        local bullet8 = Sprite("battle/bullets/ceroba/flower")
        bullet8:setPosition(Game.battle.soul.x - 20, Game.battle.soul.y - 20)
        bullet8.layer = Game.battle.soul.layer + 1
        bullet8:setOrigin(0.5, 0.5)
        Game.battle.soul.parent:addChild(bullet8)

        cutscene:wait(1.5)

        cutscene:battlerText(ceroba, "I'm just gonna\nlet you go?")

        cutscene:wait(1)
        Assets.playSound("swallow")
        ceroba:shake()
        bullet1:fadeOutAndRemove(0.3)
        bullet2:fadeOutAndRemove(0.3)
        bullet3:fadeOutAndRemove(0.3)
        bullet4:fadeOutAndRemove(0.3)
        bullet5:fadeOutAndRemove(0.3)
        bullet6:fadeOutAndRemove(0.3)
        bullet7:fadeOutAndRemove(0.3)
        bullet8:fadeOutAndRemove(0.3)
        cutscene:wait(1)
        Assets.playSound("swallow")
        ceroba:shake()
        cutscene:wait(1)
        ceroba:getActiveSprite():setAnimation("death")
        cutscene:wait(2.5)

        Assets.playSound("vaporized")
        ceroba:defeat("PACIFIED", false)
        Game.battle.arena:changeShape({565, 130})
        cutscene:wait(1)

        cutscene:after(function()
            Game.battle:setState("VICTORY")
        end, true)
    end,
}